---
version: '3.8'
services:
  db1:
    image: postgres
    environment:
      POSTGRES_PASSWORD:  intelliqit
      POSTGRES_USER:  myuser
      POSTGRES_DB: mydb
  mydminer:
    image: adminer
    ports:
      - 9999:8080
    links:
      - db1:postgres
...

