version: "3.8"
services:
  app2:
    image: adminer
    environment:
      - SERVICE_URL=http://54.227.126.232:9090
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge

